### ISSUE TITLE
Fix logo and text input labels on login page

### ISSUE THREAD

**Issue by CR96** [WildAid/o-fish-web#344] opened 2020-10-25 18:19 UTC
**Is your feature request related to a problem? Please describe.**
Labels for the application logo and text input fields on the login page are not properly read when using a screen reader.

**Describe the solution you'd like**
Correctly associate labels with their respective elements.

**Comment by Sheeri** [comment] 2020-10-26 14:59
@CR96 accepted as an issue, this is ready to work on. Would you like it to be assigned to you?

**Comment by CR96** [comment] 2020-10-27 05:48
@Sheeri Yes, please!

**Comment by Sheeri** [comment] 2020-10-27 18:49
@CR96 the issue is yours!

**Closed** 2020-10-30 19:07 UTC
Labels: accessibility/a11y, desirable: Community, enhancement, hacktoberfest
