### ISSUE TITLE
Remove Invalid DOM property "class" warning in FilterPanel component (

### ISSUE THREAD

**Issue by Dusch4593** [WildAid/o-fish-web#331] opened 2020-10-20 01:43 UTC
**Describe the bug**
Inside the component's `render()`, on line 172, I encounter a warning: 

```
Warning: Invalid DOM property `class`. Did you mean `className`?
    in span (at filter-panel.component.js:172)
    in div (at filter-panel.component.js:171)
    in div (at filter-panel.component.js:170)
    in div (at filter-panel.component.js:154)
    ...
```

**To Reproduce**
1. Build and run the app by following the instructions in the [README.md](https://github.com/WildAid/o-fish-web/blob/main/README.md) file
2. Open the browser's inspector with right-click, then  **"Inspect"**.  
3. Scroll down to line 172
4. Notice how the open `<span>` tag is typed:

```
<span class="material-icons icon-font">filter_alt</span> { filterParts.length ? `(${filterParts.length})` : "" }
```

**Expected behavior**
Because React uses JSX to allow for JavaScript to be written within markup, it is expected that any `class` attributes are typed as `className`. Therefore, a Warning will appear in the Inspector's console.

**Screenshots**
<img width="1440" alt="Screen Shot 2020-10-19 at 6 20 10 PM" src="https://user-images.githubusercontent.com/23144845/96529646-bef14300-1253-11eb-8525-db38aa738e69.png">

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra
 - Browser: Google Chrome
 - Browser Version: 86.0.4240.75

**Comment by Dusch4593** [comment] 2020-10-20 01:45
I found this while working on Issue #287. I have a PR ready to submit if that's okay.

**Comment by Sheeri** [comment] 2020-10-20 03:28
Yes,  please do! the "one at a time" guideline was meant to stop someone from "claiming" several issues and then not working on them....if you have PRs, the work is probably at least half done.... :D We love PRs!

**Comment by Dusch4593** [comment] 2020-10-20 18:48
I apologize for the confusing screenshot. You're right, it's not in the `/#/agencies` page. The "span" element I'm referring to seems to be coming from the `Boardings` component (`src/components/boardings/boardings.component.js`). Inside, starting on line 269, it renders a `FilterPanel` component: 

```
 <FilterPanel
    options={{ searchByFilter: true }}
    configuration={filterConfiguration}
    onFilterChanged={this.handleFilterChanged}
 />
```

I refreshed the page to make sure it wasn't left over from another page and I can confirm it is coming from this page: 
<img width="1440" alt="Screen Shot 2020-10-20 at 2 37 32 PM" src="https://user-images.githubusercontent.com/23144845/96629610-d4ad4980-12e1-11eb-8922-327c4f4fe6ec.png">  


It's true that this isn't reported inside the `npm start` terminal: 
<img width="675" alt="Screen Shot 2020-10-20 at 2 40 12 PM" src="https://user-images.githubusercontent.com/23144845/96629861-2fdf3c00-12e2-11eb-871b-7d63c3592eba.png">

But the browser, nonetheless, is catching this and, hence, the warning.

Below are the exact steps I took to reproduce this issue. Let me know if you still can't reproduce.

### Steps

1. Follow the setup instructions on this repo's [README](https://github.com/WildAid/o-fish-web/blob/main/README.md)

2. After running `npm start` and being directed to the localhost on the browser, log into O-FISH by entering the login credentials.

3. At the next screen, towards the top is a drop down option entitled "Boarding records". Hover the cursor over that and click on "Boardings".  --> (`http://localhost:3000/#/boardings/null`)

4. Inspect the page on the browser with right-click + **Inspect**

5. Refresh the page. (You'll then see the giant red Warning appear in the console)

**Comment by Sheeri** [comment] 2020-10-21 19:33
Hrm, I still can't reproduce that:
![Screen Shot 2020-10-21 at 3 33 13 PM](https://user-images.githubusercontent.com/1767528/96773582-bebb8980-13b2-11eb-8e9e-a8a72ca05127.png)

 Can you try it on https://wildaidsandbox-mxgfy.mongodbstitch.com - so that we know we are looking at the same code?

**Comment by Dusch4593** [comment] 2020-10-24 01:58
You're right, the `className` attribute (around line 172) is typed correctly. The state of the repo I forked to my account must have had old code that had already been corrected. Sorry for the confusion.

**Comment by Sheeri** [comment] 2020-10-26 13:39
No worries! Thanks for going on this journey with me. I will close this PR and list it as hacktoberfest-accepted so you get credit for hacktoberfest - you did good work, and that isn't invalid just because the issue was fixed by someone else.

**Closed** 2020-10-26 13:40 UTC
Labels: bug, hacktoberfest-accepted
